### ISSUE TITLE
ws错误

### ISSUE THREAD

**Issue by clcc2019** [oliverkirk-sudo/WarpGPT#23]
```yaml
2024/02/25 03:57:21 http: panic serving 127.0.0.1:36250: runtime error: invalid memory address or nil pointer dereference
goroutine 201955 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0xa23e20?, 0xfdd5a0?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
WarpGPT/pkg/plugins/service/wsstostream.GetRegisterWebsocket({0xc0051b6a00, 0x4a5})
	/root/workdir/chatgpt/warpgpt/pkg/plugins/service/wsstostream/wsstostream.go:69 +0xa9
WarpGPT/pkg/plugins/service/wsstostream.(*WssToStream).InitConnect(0xc002f37578)
	/root/workdir/chatgpt/warpgpt/pkg/plugins/service/wsstostream/wsstostream.go:111 +0x6c8
WarpGPT/pkg/plugins/api/backendapi.(*BackendProcess).ProcessMethod(0xc00021efc0)
	/root/workdir/chatgpt/warpgpt/pkg/plugins/api/backendapi/backend.go:71 +0x430
WarpGPT/pkg/common.Do[...]({0xbf7f40?, 0xc00021efc0}, {0xc001b8aa00, {0xc0086a2120, 0x30}, {0xbfe900, 0xc005af2e60}, {0xbf66c0, 0xc008e132c0}, {0xc0086a2101, ...}, ...})
	/root/workdir/chatgpt/warpgpt/pkg/common/processBody.go:17 +0x58
WarpGPT/pkg/plugins/api/backendapi.(*BackendProcess).Run.func1(0xb0d03b?)
	/root/workdir/chatgpt/warpgpt/pkg/plugins/api/backendapi/backend.go:287 +0x90
github.com/gin-gonic/gin.(*Context).Next(0xc001b8aa00)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
main.main.CORSMiddleware.func3(0xc001b8aa00)
	/root/workdir/chatgpt/warpgpt/main.go:37 +0x113
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc001b8aa00)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xde
github.com/gin-gonic/gin.(*Context).Next(...)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0003ee1a0, 0xc001b8aa00)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x65b
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0003ee1a0, {0xbf8810?, 0xc0023416c0}, 0xc003745400)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
net/http.serverHandler.ServeHTTP({0xbf66c0?}, {0xbf8810?, 0xc0023416c0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc006984630, {0xbf94c0, 0xc0003e5620})
	/usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3086 +0x5cb

```

**Comment by clcc2019** [comment]
应该是注册ws地址时失败，或者非200导致的

**Comment by oliverkirk-sudo** [comment]
添加了空ws的判断
